name: Ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    services:
      consul:
        image: consul:latest
        env:
          CONSUL_BIND_INTERFACE: eth0
        ports:
          - 8500:8500/tcp
    strategy:
      matrix:
        go-version: ["1.16", "1.13"]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    
    - uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        fail_ci_if_error: false
